project:
  type: book

book:
  title: "Data Analysis with Python"
  author: "Hung Tong"
  date: "July 2026"
  chapters:
    - index.qmd
    - 1_bikesharing.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



